### ISSUE TITLE
Improve responsiveness of sponsor page

### ISSUE THREAD

**Issue by KevinPayravi** [hackohio/ohio#110]
http://hack.osu.edu/sponsor/

**Comment by mikeletscher** [comment]
Could probably adapt the ShowOhio pre-event splash page we had before to work for this in a few minutes. @KevinPayravi

**Comment by KevinPayravi** [comment]
Already copied your ShowOHI/O CSS to the [Sponsor CSS](https://github.com/hackohio/ohio/blob/master/style/sponsor.css), just needs some tweaking. If you tackle it, great, otherwise I'll look @ it later :D

**Comment by mikeletscher** [comment]
@KevinPayravi will take a look/finish it up in the morning!

**Comment by emilyengle** [comment]
Closing out; hack.osu.edu/sponsor is gone
