### ISSUE TITLE
Add showcase RSVP button to hack.osu.edu

### ISSUE THREAD

**Issue by arnabdotorg** [hackohio/ohio#76]

**Comment by KevinPayravi** [comment]
Already have one ("Showcase"). Want to rename it? Adding "RSVP" makes the button too long :( I can look at making it double-width.

**Comment by arnabdotorg** [comment]
"Showcase RSVP"

**Comment by arnabdotorg** [comment]
:information_desk_person:

**Comment by KevinPayravi** [comment]
oop
